//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace csound6netlib {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("csound6netlib.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct Access of Channel {0} failed: {1}.
        /// </summary>
        internal static string ChannelAccessFailed {
            get {
                return ResourceManager.GetString("ChannelAccessFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleanup Failed: {0}.
        /// </summary>
        internal static string CleanupFailed {
            get {
                return ResourceManager.GetString("CleanupFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compilation failed: {0}.
        /// </summary>
        internal static string CompileFailed {
            get {
                return ResourceManager.GetString("CompileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Csound constructor - csoundCreate Failed: {0}.
        /// </summary>
        internal static string CreateFailed {
            get {
                return ResourceManager.GetString("CreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cscore {0} Failed: {1}.
        /// </summary>
        internal static string CscoreFailed {
            get {
                return ResourceManager.GetString("CscoreFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal: csound of {0} out of phase with running csound instance.
        /// </summary>
        internal static string CsoundEngineMismatch {
            get {
                return ResourceManager.GetString("CsoundEngineMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract File: {0}.
        /// </summary>
        internal static string ExtractFileFailed {
            get {
                return ResourceManager.GetString("ExtractFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Csound constructor - csoundInitialized Failed: {0}.
        /// </summary>
        internal static string InitFailed {
            get {
                return ResourceManager.GetString("InitFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PerformBuffer failed: {0}.
        /// </summary>
        internal static string PerformBufferFailed {
            get {
                return ResourceManager.GetString("PerformBufferFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perform failed: {0}.
        /// </summary>
        internal static string PerformFailed {
            get {
                return ResourceManager.GetString("PerformFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PerformKsmps failed: {0}.
        /// </summary>
        internal static string PerformKsmpsFailed {
            get {
                return ResourceManager.GetString("PerformKsmpsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in Score Data: {0}.
        /// </summary>
        internal static string ScoreFailed {
            get {
                return ResourceManager.GetString("ScoreFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Score Failure: {0}.
        /// </summary>
        internal static string SortScoreFailed {
            get {
                return ResourceManager.GetString("SortScoreFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance Start Failed: {0}.
        /// </summary>
        internal static string StartFailed {
            get {
                return ResourceManager.GetString("StartFailed", resourceCulture);
            }
        }
    }
}
